# Generated by Django 3.2.12 on 2022-04-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrapper',
            name='title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
