# Generated by Django 3.2.12 on 2022-04-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220415_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='create_date',
            field=models.DateTimeField(auto_now=True, verbose_name='작성일자'),
        ),
    ]
