# Generated by Django 3.2.12 on 2022-05-08 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='from')),
                ('end', models.DateTimeField(verbose_name='to')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='event.event')),
                ('isPermmitted', models.BooleanField(default=False)),
            ],
            bases=('event.event',),
        ),
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Ev', 'Event'), ('Va', 'Vacation'), ('Ta', 'Task')], max_length=2)),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=7, verbose_name='color')),
                ('is_private', models.BooleanField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.eventgroup'),
        ),
        migrations.AddField(
            model_name='event',
            name='relatedPeople',
            field=models.ManyToManyField(related_name='people', to=settings.AUTH_USER_MODEL),
        ),
    ]
